In [2]:
import numpy as np
import pandas as pd
from pandas import Series
import matplotlib.pyplot as plt

In [4]:
address = 'C:/Users/User/OneDrive/Documents/Final Project/Data for Analysis/working folder/RandomGeneratedRateData - V3.csv'
df = pd.read_csv(address)
parse_ages=['Ages']
df.head()

,Event Name,Order Timestamp,Status,Order ID,Barcode,TicketType,First Name,Last Name,email,email.1,...,Comment,Additional Purchases,Additional Purchases Details,Additional Purchases Options,Additional Purchases Variants,Additional Purchases Total Paid,Charity,Page URL,Raised,Fundraiser Status
0,Cycle Dublin,"Sep 27, 2020",INVALID,3804359915,81080757,100KM,Ignacia,Gutierrez,convallis.in@hotmail.edu,convallis.in@hotmail.edu,...,NaN,No,NaN,One Day Licence with Cycle Ireland,One Week Licence with Cycle Ireland,10.0,Sightsavers,https://baidu.com,2875.0,NaN
1,Cycle Cork,"Jan 18, 2021",INVALID,5787362907,91029595,100KM,Thane,Christian,porttitor.eros.nec@aol.org,porttitor.eros.nec@aol.org,...,NaN,No,NaN,One Day Licence with Cycle Ireland,One Week Licence with Cycle Ireland,10.0,Irish Cancer Society,https://guardian.co.uk,7327.0,NaN
2,Cycle Clare,"Oct 26, 2020",VALID,2321494947,80266185,50KM,Anthony,Dawson,tristique@hotmail.edu,tristique@hotmail.edu,...,NaN,Yes,Nissan,One Day Licence with Cycle Ireland,One Week Licence with Cycle Ireland,100.0,Ronald McDonald House Charities,http://cnn.com,2621.0,NaN
3,Cycle Wicklow,"Nov 17, 2020",INVALID,8323803214,97735556,50KM,Charles,Mcdaniel,nam.ac@google.edu,nam.ac@google.edu,...,NaN,Yes,backpack,One Day Licence with Cycle Ireland,One Week Licence with Cycle Ireland,20.0,Sightsavers,https://walmart.com,284.0,NaN
4,Cycle Galway,"Apr 27, 2021",VALID,9084969052,93750054,50KM,Shelly,Wong,neque.pellentesque@hotmail.net,neque.pellentesque@hotmail.net,...,NaN,No,NaN,One Day Licence with Cycle Ireland,One Week Licence with Cycle Ireland,100.0,ISPCA,https://pinterest.com,2984.0,NaN